modLoader="javafml"
loaderVersion="[30,)"

#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]]
modId="wtbw_machines"
version="${file.jarVersion}"
displayName="WTBW Machines"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="tools.png"
#credits="Thanks for this wtbw mod goes to Java" #optional
authors="Naxanria, Sunekaer"
description='''
Adds new machines
'''
[[dependencies.wtbw_machines]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.23,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wtbw_machines]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wtbw_machines]]
    modId="wtbw_lib"
    mandatory=true
    versionRange="[1.0.17,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.wtbw_machines]]
    modId="wtbw_core"
    mandatory=true
    versionRange="[1.0.13,)"
    ordering="NONE"
    side="BOTH"